### ISSUE TITLE
Page becomes unresponsive when loading all sensors

### ISSUE THREAD

**Issue by jefffohl** [nupic-community/smartthings.htm.bridge#16]
There is a significant period of time - while the data is being parsed for all the various sensors - during which the page is unresponsive. What are some ways we can mitigate this? Not have a view with all sensors?

**Comment by rhyolight** [comment]
Other options:
- load only X points per graph
- load only past 1 hour of graph data
- only show X graphs with an option to display X more at bottom of page
when pressed

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by rhyolight** [comment]
I like having a view with all the sensor graphs. It is especially useful if they can be synced (I had some troubles doing this with Dygraphs but I know it is possible because I've done it before). This would allow users to drill down on time periods on all charts at once.

I think a reasonable default data period of 1 day might make sense for all charts. They should all have some data over the past 24 hours, although some of them might take longer to load because they have lots more data. 

It would be good to mitigate this by showing some loading indicator individually for each chart. There will also be something a bit jarring when the last chart appears and they all snap to the same time period, so we may want to address that, too.

**Comment by jefffohl** [comment]
Matt, can you help me understand why a user would like to see all charts with the same time range? Are you imagining the SmartThings to always be grouped in some logical way? Such as - this is a snapshot of the Numenta office over the last day.

The problem we are running into is that some of the sensors produce a huge amount of data, and some produce very little, over a 24 hour period. With a 24 hour window, the browser really bogs down. Even if we show some visual feedback to indicate data is being loaded, that won't prevent the page locking up. The only ways I can think of preventing this are:
* Use a maximum number of rows as the default request, and set it to a reasonable number, instead of a time window.
* Perform some kind of subsampling on the server, so the client never has to render more than a certain number of rows.
* Use a server-side charting tool.

**Comment by rhyolight** [comment]
Main reason is to correlate anomalies across sensors. But we are still far from that right now. I have some backend rework to do before the HTM predictions will be good (aggregation, model param tuning). 

So for now if it is troublesome, don't worry about it.

**Comment by jefffohl** [comment]
this was fixed via #23 . By default, charts now start with just 100 rows. Though, it is still possible to lock up the page by applying a large number of rows to all of the charts on the Sensors page.
